name: Deploy to Both Regions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to both regions
      - name: Deploy to East US
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movieapp-web-eastus'
          package: .

      - name: Deploy to West Europe
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movieapp-web-westeu'
          package: .