name: Deploy Static Website to Azure Web App - movieapp-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movieapp-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
