name: Deploy MovieApp to Azure Web Apps (Multi-Region)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        region: ['eastus', 'westeurope']
    env:
      APP_NAME: movieapp-web-${{ matrix.region }}
      RESOURCE_GROUP: slp_movieapp-rg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ${{ matrix.region }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: .
          slot-name: staging  # Using slots for zero-downtime deployment

      - name: Swap slots (Production)
        if: matrix.region == 'eastus'  # Only swap primary region
        run: |
          az webapp deployment slot swap \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --slot staging \
            --target-slot production

      - name: Verify deployment
        run: |
          echo "Deployed to: https://${{ env.APP_NAME }}.azurewebsites.net"
          curl -s https://${{ env.APP_NAME }}.azurewebsites.net/healthcheck | jq .