name: Deploy MovieApp to Both Regions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to East US
      - name: Deploy to East US App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movieapp-web-eastus'
          publish-profile: ${{ secrets.EASTUS_PUBLISH_PROFILE }}
          package: .
        
      # Deploy to West Europe  
      - name: Deploy to West Europe App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movieapp-web-westeu'
          publish-profile: ${{ secrets.WESTEU_PUBLISH_PROFILE }}
          package: .

      - name: Verify deployments
        run: |
          echo "East US deployed: https://movieapp-web-eastus.azurewebsites.net"
          echo "West EU deployed: https://movieapp-web-westeu.azurewebsites.net"